id: P005521
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:56:11.371283
source_metadata:
  id: bdr:W1KG11665
  title: གསུང་འབུམ། ངག་དབང་མཁྱེན་རབ།
  author: ''
  volumes:
    63e69cf589264865a28108b8009984ef:
      image_group_id: I1KG11676
      title: ''
      volume_number: 1
      total_pages: 738
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
